### ISSUE TITLE
Referência de origem ausente

### ISSUE THREAD

**Issue by mirandadam** [manoelcampos/ft-unb-latex-template#1]
Olá Manoel, parabéns pela criação deste repositório! Concluo minha dissertação este sementre no PPMEC e o seu material será muito útil.

Senti falta de um link para o material original do prof. Geovany. Você recebeu isso direto dele? Ele autorizou publicar o material como CC BY-NC-SA 3.0?

Talvez fosse interessante para a FT ter uma licença comercial de uso (esse "NC" quer dizer não comercial), como a CC BY-SA, caso seja um trabalho com origem na indústria.

**Comment by manoelcampos** [comment]
Olá Daniel, primeiramente obrigado.

O template obtive na época em que eu estava fazendo mestrado no departamento de Engenharia Elétrica, por meio dos integrantes do grupo de pesquisa. 
Solicitei permissão do professor Geovany para publicar o material. Na época, mandei email a ele, informei que estava dando os devidos créditos e falei sobre a licença. Ele falou que estava tudo bem.

Por mim, tanto faz alterar a licença, eu precisaria contactar o prof. Geovany e verificar se ele tem alguma restrição neste sentido. Acho que seria interessante para a FT. Se quiser conversar a respeito em privado, pode me enviar email para manoelcampos (gmail).

Quanto ao link original, não tenho para incluir. O template foi iniciado antes de o GitHub se tornar popular e obtive ele por meio de um zip compartilhando entre os integrantes do LabTVDI na UnB na época.
