### ISSUE TITLE
Alterar tipo de licença

### ISSUE THREAD

**Issue by AndreLaranjeira** [manoelcampos/ft-unb-latex-template#2]
Gostaria de utilizar esse template para a monografia do meu trabalho de graduação, mas fiquei com uma dúvida em relação a licença utilizada.

A licença utilizada afirma que: "You may not offer or impose any terms on the Work that restrict the terms of this License or the ability of the recipient of the Work to exercise the rights granted to that recipient under the terms of the License.". Um direito concedido por essa licença é: "to Reproduce the Work, to incorporate the Work into one or more Collections, and to Reproduce the Work as incorporated in the Collections;". Isso parece ir contra o propósito de uma monografia, pois até o texto na capa da monografia de exemplo afirma que: "O autor se reserva a outros direitos de publicação e nenhuma parte desta dissertação de Mestrado pode ser reproduzida sem a autorização por escrito do autor.".

Diante desse impasse, gostaria de sugerir que a licença utilizada fosse mudada de uma licença do tipo [CC BY-NC-SA](https://creativecommons.org/licenses/by-nc-sa/4.0/) para uma licença do tipo [CC BY-NC](https://creativecommons.org/licenses/by-nc/4.0/), permitindo ao usuário que utilizar o template a imposição de restrições sobre a reprodução da monografia.

Desde já agradeço pela atenção.

**Comment by manoelcampos** [comment]
Acredito que a licença se aplica apenas aos arquivos do template. Como existe uma separação total entre os arquivos com o conteúdo que você criar e os do template, não vejo problema.
Você só precisaria compartilhar nos mesmos temos se fizesse alterações no template.
De qualquer forma, se você ainda tem receio quanto a isso, altero a licença, pois o objetivo é facilitar a vida de quem for usar.

**Comment by AndreLaranjeira** [comment]
Ah, entendi. Eu fiquei meio confuso porque o texto base da licença em si não mencionava essa distinção entre uso do template e modificação do template, apenas agrupando qualquer forma de modificação ao material sob o termo "Adaptação".

Ao perguntar mais sobre o assunto, descobri que a cláusula de shareAlike é comum em trabalhos acadêmicos para que estes possam ser reproduzidos e divulgados sem maiores restrições comerciais, então vou utilizar o template com a licença atual modificando a capa da monografia para refletir os termos da licença de livre redistribuição com atribuição (acho que é o curso de ação mais simples a ser adotado).

Obrigado por esclarecer minha dúvida.

**Comment by manoelcampos** [comment]
Pois é, mas minha dúvida é se outros usuários deixam de usar o template por acharem que precisam compartilhar a monografia/dissertação/tese. Se este for o caso, acho que a outra licença seria melhor mesmo. O que acha?

**Comment by AndreLaranjeira** [comment]
Nesse caso, talvez mudar a licença para uma CC sem shareAlike fosse o ideal mesmo (pode ser que até simplifique os termos de uso, mas não cheguei a comparar ambos os documentos). Uma outra sugestão seria especificar no README.md que diferentes licenças se aplicam para aqueles que querem utilizar o template para suas monografias/dissertações/teses e para aqueles que querem utilizar o template com outros propósitos (criar novos templates, etc...). Acho que depende realmente da propósito desejado com a cláusula de shareAlike na licença atual.

**Comment by manoelcampos** [comment]
Pronto, licença alterada. Obrigado por levantar a questão.
